/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "funciones.h"

double v_saldo = 10000.00;

double *
banco_1_svc(operaciones *argp, struct svc_req *rqstp)
{

	static double result;
	int op = argp->op;
	double cant = argp->cant;
	double saldo = v_saldo;

    switch(op){
        case 1:
            v_saldo = v_saldo + cant;
		    result = v_saldo;
        break;
        case 2:
            v_saldo = v_saldo - cant;
		    result = v_saldo;
        break;
    }

	
	return &result;
}
