/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FUNCIONES_H_RPCGEN
#define _FUNCIONES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operaciones {
	double saldo;
	double cant;
	int op;
};
typedef struct operaciones operaciones;

#define SERVIDOR_BANCARIO 0x20000001
#define VERSION_BANCO 1

#if defined(__STDC__) || defined(__cplusplus)
#define banco 1
extern  double * banco_1(operaciones *, CLIENT *);
extern  double * banco_1_svc(operaciones *, struct svc_req *);
extern int servidor_bancario_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define banco 1
extern  double * banco_1();
extern  double * banco_1_svc();
extern int servidor_bancario_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operaciones (XDR *, operaciones*);

#else /* K&R C */
extern bool_t xdr_operaciones ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FUNCIONES_H_RPCGEN */
