/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "funciones.h"


void
servidor_bancario_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	operaciones  banco_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SERVIDOR_BANCARIO, VERSION_BANCO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    int op = 0;
    double cant = 0.00;

    printf("\nBIENVENIDO\n");
    printf("Seleccione la operacion que desee realizar:\n");
	printf("1. Depositar\n");
	printf("2. Retirar\n");
    printf("Opcion : ");
	scanf("%d", &op);

    printf("Ingresar cantidad de dinero que desea operar\n");
	scanf("%lf", &cant);
   
    banco_1_arg.op = op;
	banco_1_arg.cant = cant;
	banco_1_arg.saldo = 0.00;
	result_1 = banco_1(&banco_1_arg, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
        printf("Saldo actual: $%lf ", *result_1);
        printf("\n");
        printf("Cantidad manejada $%lf \n", cant);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
   
int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	servidor_bancario_1 (host);
exit (0);
}
