/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "funciones.h"

bool_t
xdr_operaciones (XDR *xdrs, operaciones *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->saldo))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->cant))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->op))
		 return FALSE;
	return TRUE;
}
